const productos_a_mover = [
  { id: 1, nombre: 'comida corrida pechuga rellena', imagen: 'https://i.ibb.co/tY5BBVm/10.jpg', cantidad: 0, precio: 75, extra: "", total: 0 },
  { id: 2, nombre: 'comida corrida bistec a la mexicana', imagen: 'https://i.ibb.co/fx68w4x/8.jpg', cantidad: 0, precio: 75, extra: "", total: 0 },
  { id: 3, nombre: 'comida corrida pechuga asada', imagen: 'https://i.ibb.co/YNVHtd5/18.jpg', cantidad: 0, precio: 75, extra: "", total: 0 },
  { id: 4, nombre: 'desayuno tarde club sanwich', imagen: 'https://i.ibb.co/BG1bq0m/24.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 5, nombre: 'desayuno huevo a la mexicana', imagen: 'https://i.ibb.co/Y0rSjrt/4-huevo-a-la-mexicana.jpg', cantidad: 0, precio: 40, extra: "", total: 0 },
  { id: 6, nombre: 'desayuno huevo ranchero', imagen: 'https://i.ibb.co/rFzmPGh/5-huevo-ranchero.jpg', cantidad: 0, precio: 35, extra: "", total: 0 },
  { id: 7, nombre: 'desayuno huevo motuleño', imagen: 'https://i.ibb.co/Z8zrsyV/6-huevo-motule-o.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 8, nombre: 'desayuno huevo estrellado', imagen: 'https://i.ibb.co/sR2MCp8/7-huevos-estrellados.jpg', cantidad: 0, precio: 30, extra: "", total: 0 },
  { id: 9, nombre: 'desayuno omelet', imagen: 'https://i.ibb.co/wJG7Rp2/8-omelet.jpg', cantidad: 0, precio: 40, extra: "", total: 0 },
  { id: 10, nombre: 'desayuno huevo divorciados', imagen: 'https://i.ibb.co/VBC1fLd/9-huevos-divorciados.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 11, nombre: 'tarde pechuga empanizada', imagen: 'https://i.ibb.co/61x0s7d/10-p3chuga-empanizada.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 12, nombre: 'desayuno chilaquiles', imagen: 'https://i.ibb.co/NsKLcgb/11-chilaquiles.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 13, nombre: 'desayuno enchiladas suisas', imagen: 'https://i.ibb.co/1Zrjpdw/9.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 14, nombre: 'desayuno enmoladas', imagen: 'https://i.ibb.co/QPrX4bD/12-enmoladas.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 15, nombre: 'desayuno tacos dorados', imagen: 'https://i.ibb.co/dj1wQT2/13-tacos-dorados.jpg', cantidad: 0, precio: 40, extra: "", total: 0 },
  { id: 16, nombre: 'desayuno hotcakes', imagen: 'https://i.ibb.co/VjGTqQ9/15-hotkakes.jpg', cantidad: 0, precio: 40, extra: "", total: 0 },
  { id: 17, nombre: 'desayuno sincronisadas', imagen: 'https://i.ibb.co/f9rWzg4/15-sincronisadas.jpg', cantidad: 0, precio: 40, extra: "", total: 0 },
  { id: 18, nombre: 'desayuno molletes', imagen: 'https://i.ibb.co/MGnB1dP/19.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 19, nombre: 'tarde torta bistek', imagen: 'https://i.ibb.co/D9LsLFj/16-torta-de-bistec.jpg', cantidad: 0, precio: 35, extra: "", total: 0 },
  { id: 20, nombre: 'desayuno coctel de frutas', imagen: 'https://i.ibb.co/yBZXYng/13.jpg', cantidad: 0, precio: 50, extra: "", total: 0 },
  { id: 21, nombre: 'desayuno cafe', imagen: 'https://i.ibb.co/ZBhmptQ/17-cafe.jpg', cantidad: 0, precio: 10, extra: "", total: 0 },
  { id: 22, nombre: 'desayuno cafe con leche', imagen: 'https://i.ibb.co/LCTR0sW/18-cafe-con-leche.jpg', cantidad: 0, precio: 20, extra: "", total: 0 },
  { id: 23, nombre: 'desayuno jugo de naranja', imagen: 'https://i.ibb.co/cbd6w41/19-jugo-de-naranja.jpg', cantidad: 0, precio: 28, extra: "", total: 0 },
  
];